const LOGIN_ERRORS = {
    NO_TRUST_CONFIGURED: 'NO_TRUST_CONFIGURED',
    TOKEN_EXCHANGE_FAILED: 'TOKEN_EXCHANGE_FAILED',
    STATE_EXPIRED: 'STATE_EXPIRED',
    FINGERPRINT_MISMATCH: 'FINGERPRINT_MISMATCH',
    INVALID_REQUEST: 'INVALID_REQUEST',
    SERVER_ERROR: 'SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_OIDC_PROVIDER: 'INVALID_OIDC_PROVIDER'
};

const Constants = {
    API_ERROR_CODES: {
        UNIQUE_ERROR: 'UNIQUE_ERROR',
        KEY_CONFIGURATION_NOT_FOUND: 'KEY_CONFIGURATION_NOT_FOUND'
    },
    FORBIDDEN_ERROR_CODES: {
        FORBIDDEN: 'FORBIDDEN',
        MULTIPLE_ROLES_NOT_ALLOWED: 'MULTIPLE_ROLES_NOT_ALLOWED',
        NO_TENANT_ACCESS: 'NO_TENANT_ACCESS',
        TENANT_BLOCKED: 'TENANT_BLOCKED',
        FORBIDDEN_GENERIC: 'FORBIDDEN_GENERIC',
        AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
        ZERO_ROLES_NOT_ALLOWED: 'ZERO_ROLES_NOT_ALLOWED',
        MULTIPLE_UNSUCCESSFUL_LOGIN_ATTEMPTS: 'MULTIPLE_UNSUCCESSFUL_LOGIN_ATTEMPTS',
        LOGGED_OUT: 'LOGGED_OUT',
        NO_PAGE_ACCESS: 'NO_PAGE_ACCESS'
    },
    LOGIN_ERRORS: LOGIN_ERRORS
};

export default Constants;