const Constants = {
    API_ERROR_CODES: {
        UNIQUE_ERROR: 'UNIQUE_ERROR',
        KEY_CONFIGURATION_NOT_FOUND: 'KEY_CONFIGURATION_NOT_FOUND'
    },
    FORBIDDEN_ERROR_CODES: {
        FORBIDDEN: 'FORBIDDEN',
        MULTIPLE_ROLES_NOT_ALLOWED: 'MULTIPLE_ROLES_NOT_ALLOWED',
        NO_TENANT_ACCESS: 'NO_TENANT_ACCESS',
        FORBIDDEN_GENERIC: 'FORBIDDEN_GENERIC',
        AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
        ZERO_ROLES_NOT_ALLOWED: 'ZERO_ROLES_NOT_ALLOWED'
    }
};

export default Constants;
