{{- if .Values.ui.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  {{- with .Values.ui.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.ui.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.ui.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.ui.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- with .Values.ui.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
      {{- with .Values.ui.podDisruptionBudget.additionalSelectorLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
