name: Checkmarx Scan

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
  # Run on all PRs and merges to integration and release branches
  pull_request:
    branches:
      - main
      - 'releases/**'
  push:
    branches:
      - main
      - 'releases/**'

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif

    # The type of runner that the job will run on
    runs-on: [ self-hosted, solinas ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACTION_REPO_READ }}
      # This step creates the Checkmarx One scan
      - name: Checkmarx One scan
        timeout-minutes: 30
        uses: checkmarx/ast-github-action@main
        with:
          project_name: KMS20-${{ github.event.repository.name }}
          base_uri: https://checkmarx.tools.sap
          cx_client_id: ${{ secrets.CX_CLIENT_ID }} 
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }} 
          cx_tenant: sap # This should be replaced by your tenant for Checkmarx One
          additional_params: --scan-types sast --output-path . --sast-preset-name SAP_Corp_Microservice_Backend --sast-incremental --sast-filter **/*.go
