name: Piper workflow

on:
  push:
    inputs:
      piper-version:
        required: false
        type: string
        default: 'latest'
      sap-piper-version:
        required: false
        type: string
        default: 'latest'
      runs-on:
        required: false
        type: string
        default: '[ "self-hosted" ]'
      custom-defaults-paths:
        required: false
        type: string
        default: ''
      custom-stage-conditions-path:
        required: false
        type: string
        default: ''
      checkout-submodules:
        required: false
        type: string
        default: 'false'
      checkout-lfs:
        required: false
        type: string
        default: 'false'

  workflow_dispatch:

jobs:
  init-stage:
    uses: project-piper/piper-pipeline-github/.github/workflows/init.yml@v1.32.0
    secrets: inherit

  piper-build-stage:
    needs: [init-stage]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      on-productive-branch: ${{ needs.init-stage.outputs.on-productive-branch }}
      active-stages-map: ${{ needs.init-stage.outputs.active-stages-map }}
      active-steps-map: ${{ needs.init-stage.outputs.active-steps-map }}
      pipeline-env: ${{ needs.init-stage.outputs.pipeline-env }}
      is-optimized-and-scheduled: ${{ needs.init-stage.outputs.is-optimized-and-scheduled }}
      extensibility-enabled: true # this does enable the PreBuild extensibility

  post-stage:
    needs: [ init-stage, piper-build-stage, compliance, checkmarx, sonar, lint ]
    if: always() && !cancelled() && fromJSON(needs.init-stage.outputs.active-stages-map).Post == true
    uses: project-piper/piper-pipeline-github/.github/workflows/post.yml@v1.32.0
    secrets: inherit
    with:
      active-stages-map: ${{ needs.init-stage.outputs.active-stages-map }}
      active-steps-map: ${{ needs.init-stage.outputs.active-steps-map }}
      pipeline-env: ${{ needs.piper-build-stage.outputs.pipeline-env }}
      on-productive-branch: ${{ needs.init-stage.outputs.on-productive-branch }}
      is-optimized-and-scheduled: ${{ needs.init-stage.outputs.is-optimized-and-scheduled }}

  release:
    if: ${{ github.ref == 'refs/heads/main' && vars.RELEASE == 'true' }}
    needs: [ post-stage ]
    env:
      PIPER_ACTION_GITHUB_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PIPER_ACTION_SAP_PIPER_OWNER: project-piper
      PIPER_ACTION_SAP_PIPER_REPOSITORY: sap-piper
      PIPER_vaultAppRoleID : ${{ secrets.PIPER_VAULTAPPROLEID }}
      PIPER_vaultAppRoleSecretID: ${{ secrets.PIPER_VAULTAPPROLESECRETID }}
    runs-on: self-hosted
    steps:
     - uses: actions/checkout@v4
       with:
         token: ${{ secrets.GH_ACTION_REPO_READ }}
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
     - name: GetVersion
       id: GetVersion
       run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
     - name: Print Version
       run: echo ${{ steps.GetVersion.outputs.version }}
     - name: Create tag
       uses: actions/github-script@v5
       with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.GetVersion.outputs.version }}',
            sha: context.sha
          })
     - uses: release-drafter/release-drafter@v6
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GHE_HOST: "github.tools.sap"
       with:
         commitish: main
         tag: ${{ steps.GetVersion.outputs.version }}
         version: ${{ steps.GetVersion.outputs.version }}
         
  lint:
    needs: [init-stage]
    uses: ./.github/workflows/ui-lint.yaml
    secrets: inherit
        
  checkmarx:
    needs: [init-stage]
    uses: ./.github/workflows/checkmarx.yaml
    with:
      project-name: ${{ vars.CHECKMARX_PROJECT_NAME }}
    secrets: inherit

  sonar:
    needs: [init-stage]
    uses: ./.github/workflows/sonarqube.yaml
    secrets: inherit

  # Only run mend on release branch
  mend:
    if: ${{ fromJSON(needs.init-stage.outputs.on-productive-branch) }}
    needs: [init-stage]
    uses: ./.github/workflows/mend.yaml
    secrets: inherit

  # Only run compliance on release branch
  compliance:
    needs: [ mend ]
    if: ${{ fromJSON(needs.init-stage.outputs.on-productive-branch) }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_REPO_READ }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Run PPMS Compliance Check
        uses: SAP/project-piper-action@2c5592ddbeac49b08e71fef12aea8066dd26c547
        env:
          PIPER_vaultAppRoleID: ${{ secrets.PIPER_VAULTAPPROLEID }}
          PIPER_vaultAppRoleSecretID: ${{ secrets.PIPER_VAULTAPPROLESECRETID }}
          PIPER_ACTION_GITHUB_ENTERPRISE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PIPER_ACTION_GITHUB_ENTERPRISE_URL: https://github.tools.sap
          PIPER_ACTION_SAP_PIPER_OWNER: project-piper
          PIPER_ACTION_SAP_PIPER_REPOSITORY: sap-piper
          PIPER_whitesourceProductName: "SHC - KMS20"
        with:
          step-name: sapCheckPPMSCompliance
          flags: |
            --username ${{ secrets.PPMS_USER }}
            --password ${{ secrets.PPMS_PASSWORD }}
            --ppmsID 73555000100200023677
            --uploadChangeRequest true
            --whitesourceProductToken ${{ secrets.WS_PRODUCTTOKEN }}
            --whitesourceProjectNames "kms-ui - main"
