name: SonarQube scan

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: [self-hosted, solinas]
    container: public.int.repositories.cloud.sap/ubuntu:22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install chrome and curl
      run: |
        apt update
        apt install -y curl net-tools
        apt install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt install -y ./google-chrome-stable_current_amd64.deb
    - name: Start webserver
      run: |
        npm install
        npm run start:test&
        coproc read -t 10 && wait "$\!" || true
        npm run test
    - uses: actions/upload-artifact@v3
      with:
        name: test-coverage-report
        path: coverage/lcov.info

  sonarqube-scan:
    needs: unit-tests
    name: Run SonarQube scan
    runs-on: [self-hosted, solinas]
    container: python:3.9.16-slim
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Update Ubuntu
        run: |
          apt update
      - name: Install Ubuntu dependencies
        run: |
          apt install -y curl jq zip unzip
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTION_REPO_READ }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/download-artifact@v3
        with:
          name: test-coverage-report
          path: webapp/coverage
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=webapp/coverage/*/lcov.info
            -Dsonar.coverage.skip=${{ vars.SONAR_QUBE_COVERAGE_SKIP }}
            -Dsonar.exclusions=${{ vars.SONAR_QUBE_EXCLUSIONS }}
            -Dsonar.verbose=${{ vars.SONAR_QUBE_VERBOSE_LOGGING }}
            -Dsonar.projectKey=${{ vars.SONAR_QUBE_PROJECT_KEY_PREFIX }}-${{ github.event.repository.name }}
        #${{ steps.repo-name.outputs.repository-name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Get sonarqube url
        run: echo "[SonarQube branch scan details](${{ vars.SONAR_QUBE_PROJECT_URL }}-${{ github.event.repository.name }}&pullRequest=$PR_NUMBER)" >> $GITHUB_STEP_SUMMARY
        env:
          PR_NUMBER: ${{ github.event.number }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
